[workspace]

members = [
    "ai2048_bin",
    "ai2048_lib",
]

[profile]

[profile.dev]
codegen-units = 4
panic = "abort"

[profile.release]
debug = true
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
