[package]
name = "ai2048"
version = "0.1.0"
authors = ["Victor Gavrish <victor.gavrish@gmail.com>"]

[dependencies]
rand = "0.3"
time = "0.1"
itertools = "0.4"
lazycell = "0.2"
fnv = "1.0"

[[bin]]
name = "ai2048_bin"

[profile.release]
debug = true