[workspace]

members = [
    "ai2048-bin",
    "ai2048-lib",
]

[profile]

[profile.dev]
codegen-units = 4
panic = "abort"

[profile.release]
debug = true
lto = true
codegen-units = 1
panic = "abort"
