[package]
authors = ["Victor Gavrish <victor.gavrish@gmail.com>"]
license = "LGPL"
name = "ai2048-lib"
version = "0.1.0"
edition = "2018"

[features]
default = ["hashbrown", "fnv"]

[dependencies]
lazy_static = "1.2"
rand = "0.5"
bytecount = "0.4"
cfg-if = "0.1.6"

fnv = { version = "1.0", optional = true }
fxhash = { version = "0.2.1", optional = true }

hashbrown = { version = "0.1", optional = true }
indexmap = { version = "1.0.2", optional = true }
